# customer module
name = "Customer Module"
version = "1.0.0"
id = "yoji.customer-module"
priority = 100
entry_point = "CustomerModule:CustomerModule"

[provides]
default-customer = "1.0"

[requires]
default-shop = ">=1.0"